#!/bin/bash

# Modify the following lines to reflect the accurate paths to the libraries on your system.
export RASPA_DIR=~/RASPA2/simulations
export ZEO_DIR=~/zeo++-0.3
export CPP_DIR=~/surface-csampler
export GLOST_DIR=~/glost

# The following lines should not be modified (unless you know what you are doing).
export DYLD_LIBRARY_PATH=${RASPA_DIR}/lib
export LD_LIBRARY_PATH=${RASPA_DIR}/lib
export MATSCREEN=$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd) # current dir path
