#! /bin/bash
node=$(hostname)
source ${dirname $(dirname $0)}/set_environment

cd "$(dirname "$0")"
${ZEO_DIR}/network -ha -sa ${2} ${2} N_cycles Output/results_${1}_${2}.sa ${RASPA_DIR}/share/raspa/structures/cif/${1}.cif &&
echo "structure ${1} radius ${2} surface Simulation DONE on $node"
