#! /bin/bash
node=$(hostname)
export MATSCREEN=/home/emmanuel/Documents/material-screening
source ${MATSCREEN}/set_environment

cd "$(dirname "$0")" 
${ZEO_DIR}/network -ha -block ${2} N_cycles Output/${1}.block ${RASPA_DIR}/share/raspa/structures/cif/${1}.cif &&
echo "structure ${1} radius ${2} block Simulation DONE on $node"
