#! /bin/bash
node=$(hostname)
source ${MATSCREEN}/set_environment

cd "$(dirname "$0")"
${ZEO_DIR}/network -r rad_uff_298K.rad \
-ha -res Output/results_${1}.res ${RASPA_DIR}/share/raspa/structures/cif/${1}.cif &&
echo "structure ${1} radius ${2} pore Simulation DONE on $node"
