#! /bin/bash
node=$(hostname)
export MATSCREEN=/home/emmanuel/Documents/material-screening
source ${MATSCREEN}/set_environment

cd "$(dirname "$0")" 
${ZEO_DIR}/network -ha -chan ${2} Output/results_${1}_${2}.chan ${RASPA_DIR}/share/raspa/structures/cif/${1}.cif &&
echo "structures ${1} radius ${2} channel Simulation DONE on $node"
