#! /bin/bash
node=$(hostname)
source ./set_environment

cd "$(dirname "$0")"
${ZEO_DIR}/network -r rad_uff_298K.rad \
-ha -sa ${2} ${2} N_cycles Output/results_${1}_${2}.sa ${RASPA_DIR}/share/raspa/structures/cif/${1}.cif &&
echo "structure ${1} radius ${2} surface Simulation DONE on $node"
