#! /bin/bash
node=$(hostname)
source ${RASPASCREEN}/set_environement

cd "$(dirname "$0")" 
${ZEO_DIR}/network -ha -vol ${2} ${2} NCYCLES Output/results_${1}_${2}.vol ${RASPA_DIR}/share/raspa/structures/cif/${1}.cif &&
echo "structures ${1} radius ${2} Simulation DONE on $node"
