#! /bin/bash
node=$(hostname)
source ${RASPASCREEN}/set_environment

cd "$(dirname "$0")" 
${ZEO_DIR}/network -ha -res Output/results_${1}.res ${RASPA_DIR}/share/raspa/structures/cif/${1}.cif &&
echo "structures ${1} radius ${2} Simulation DONE on $node"
