#! /bin/bash
node=$(hostname)
export RASPA_DIR=$CCCSCRATCHDIR/Simulations
export DYLD_LIBRARY_PATH=${RASPA_DIR}/lib
export LD_LIBRARY_PATH=${RASPA_DIR}/lib
cd "$(dirname "$0")" 
cp INPUT Scripts/simulation_${1}.input &&  
sed -i "s/Arg/${1}/g" Scripts/simulation_${1}.input &&
sed -i "s/UNITCELL/${2}/g" Scripts/simulation_${1}.input &&
echo "${1} ${2} Script DONE on $node" 
${RASPA_DIR}/bin/simulate -i Scripts/simulation_${1}.input > /dev/null 2>&1 &&
echo "${1} ${2} Simulation DONE $node"
