#! /bin/bash
node=$(hostname)
source ./set_environment

cd "$(dirname "$0")"
NEWINPUT=Scripts/simulation_${1}_${3}_${4}.input
cp INPUT $NEWINPUT
sed -i "s/Arg/${1}/g;s/UNITCELL/${2}/g;s/TEMPERATURE/${3}/g;s/PRESSURES/${4}/g;s/RESTART/${5}/g;s/N_init/${6}/g" $NEWINPUT
echo "Script DONE on $node: ${1} ${2} ${3} ${4} ${6}"
mkdir Output/${1}
cd Output/${1}
${RASPA_DIR}/bin/simulate -i ../../$NEWINPUT > /dev/null 2>&1
echo "Simulation DONE on $node: ${1} ${2} ${3} ${4} ${6}"
#mv MSDOrderN/System_0/msd_self_MOLECULE_0.dat ../msd_self_MOLECULE_${1}.dat
#rm -rf Movies
#rm -rf VTK
