#! /bin/bash
node=$(hostname)
source ./set_environment
cd "$(dirname "$0")"

NEWINPUT=Scripts/simulation_${1}_${3}.input
cp INPUT $NEWINPUT
sed -i "s/Arg/${1}/g;s/UNITCELL/${2}/;s/TEMPERATURE/${3}/;s/POINT_NUMBER/0/;s/MOL_CREATION/1/;s/RESTART_MODE/no/" $NEWINPUT
echo "${1} ${2} first Script DONE on $node"
${RASPA_DIR}/bin/simulate -i $NEWINPUT > /dev/null 2>&1
IFS=$'\n' read -d '' -r -a lines < Coordinates/${1}.csv
len=${#lines[@]}
for (( i=1; i<$len; i++ ))
do
  line=(${lines[$i]})
  cp INPUT $NEWINPUT
  sed -i "s/Arg/${1}/g;s/UNITCELL/${2}/;s/TEMPERATURE/${3}/;s/POINT_NUMBER/$i/;s/MOL_CREATION/0/;s/RESTART_MODE/yes/" $NEWINPUT
  file=$(ls Restart/System_0/restart_${1}_*_$((i-1)))
  base=$(basename -- "${file}")
  name=${base%_*}
  cp ${file} RestartInitial/System_0/${name}_$i
  sed -i "48s/.*/Adsorbate-atom-position: 0 0 ${line[0]} ${line[1]} ${line[2]}/" RestartInitial/System_0/${name}_$i
  ${RASPA_DIR}/bin/simulate -i $NEWINPUT > /dev/null 2>&1
  echo "${1} ${2} ${3} point number $i calculated"
  rm RestartInitial/System_0/${name}_$i
  rm $file
done
rm Restart/System_0/${name}_$i
echo "${1} ${2} ${3} Simulation DONE on $node"
rm $NEWINPUT
