#! /bin/bash
node=$(hostname)
source $MATSCREEN/set_environment

cd "$(dirname "$0")"
trimmedpressures=`echo ${3} | sed 's/ //g'`
NEWINPUT=Scripts/simulation_${1}_${trimmedpressures}.input
cp INPUT $NEWINPUT

sed -i "s/Arg/${1}/g;s/UNITCELL/${2}/g;s/PRESSURES/${3}/g;s/RESTART/${4}/g;s/N_init/${5}/g" $NEWINPUT

NUMCATION='0'
ISRESTART=`grep -Po "RestartFile[[:space:]]+\K.*" $NEWINPUT`
if [ $ISRESTART == "no" ];
then
    NUMCATION=`grep "^Alz_" $RASPA_DIR/share/raspa/structures/cif/${1}.cif | wc -l`
fi

sed -i "s/NUMCATION/${NUMCATION}/g" $NEWINPUT
echo "Script DONE on $node: ${1} ${2} ${trimmedpressures} ${5}"
${RASPA_DIR}/bin/simulate -i $NEWINPUT >/dev/null
echo "Simulation DONE on $node: ${1} ${2} ${trimmedpressures} ${5}"
