#! /bin/bash
node=$(hostname)
source ./set_environment
cd "$(dirname "$0")"

trimmedpressures=`echo ${4} | sed 's/ //g'`
NEWINPUT=Scripts/simulation_${1}_${3}_${trimmedpressures}.input
cp INPUT $NEWINPUT
sed -i "s/Arg/${1}/g;s/UNITCELL/${2}/;s/TEMPERATURE/${3}/g;s/PRESSURES/${4}/g;s/RESTART/${5}/g;s/N_init/${6}/g;s/POINT_NUMBER/0/;s/MOL_CREATION/1/;s/RESTART_MODE/no/" $NEWINPUT
echo "first Script DONE on $node: ${1} ${2} ${3} ${trimmedpressures} ${5}"
${RASPA_DIR}/bin/simulate -i $NEWINPUT > /dev/null 2>&1
IFS=$'\n' read -d '' -r -a lines < Coordinates/${1}.csv
len=${#lines[@]}
for (( i=1; i<$len; i++ ))
do
  line=(${lines[$i]})
  cp INPUT $NEWINPUT
  sed -i "s/Arg/${1}/g;s/UNITCELL/${2}/;s/TEMPERATURE/${3}/g;s/PRESSURES/${4}/g;s/RESTART/${5}/g;s/N_init/${6}/g;s/POINT_NUMBER/$i/;s/MOL_CREATION/0/;s/RESTART_MODE/yes/" $NEWINPUT
  file=$(ls Restart/System_0/restart_${1}_*_$((i-1)))
  base=$(basename -- "${file}")
  name=${base%_*}
  cp ${file} RestartInitial/System_0/${name}_$i
  sed -i "48s/.*/Adsorbate-atom-position: 0 0 ${line[0]} ${line[1]} ${line[2]}/" RestartInitial/System_0/${name}_$i
  ${RASPA_DIR}/bin/simulate -i $NEWINPUT > /dev/null 2>&1
  echo "point number $i calculated: ${1} ${2} ${3} ${trimmedpressures} ${5}"
  rm RestartInitial/System_0/${name}_$i
  rm $file
done
rm Restart/System_0/${name}_$i
echo "Simulation DONE on $node: ${1} ${2} ${3} ${trimmedpressures} ${5}"
rm $NEWINPUT
