#! /bin/bash
node=$(hostname)
source ./set_environment

cd "$(dirname "$0")"
cp INPUT Scripts/simulation_${1}.input

sed -i "s/Arg/${1}/g;s/UNITCELL/${2}/g" Scripts/simulation_${1}.input

NUMCATION='0'
ISRESTART=`grep -Po "RestartFile[[:space:]]+\K.*" Scripts/simulation_${1}.input`
if [ $ISRESTART == "no" ];
then
    NUMCATION=`grep "^Alz_" $RASPA_DIR/share/raspa/structures/cif/${1}.cif | wc -l`
fi

sed -i "s/NUMCATION/${NUMCATION}/g" Scripts/simulation_${1}.input
echo "${1} ${2} Script DONE on $node"
${RASPA_DIR}/bin/simulate -i Scripts/simulation_${1}.input >/dev/null
echo "${1} ${2} Simulation DONE on $node"
