#! /bin/bash
node=$(hostname)
source ./set_environment

cd "$(dirname "$0")"
NEWINPUT=Scripts/simulation_${1}_${3}.input
cp INPUT $NEWINPUT
sed -i "s/Arg/${1}/g;s/UNITCELL/${2}/g;s/TEMPERATURE/${3}/" $NEWINPUT
echo "${1} ${2} ${3} Script DONE on $node"
mkdir Output/${1}
cd Output/${1}
${RASPA_DIR}/bin/simulate -i ../../$NEWINPUT > /dev/null 2>&1
echo "${1} ${2} ${3} Simulation DONE on $node"
#mv MSDOrderN/System_0/msd_self_MOLECULE_0.dat ../msd_self_MOLECULE_${1}.dat
#rm -rf Movies
#rm -rf VTK
